# Generated by Django 3.2 on 2021-04-18 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
        ('Transferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='origin_account',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.account', verbose_name='Cuenta de origen'),
        ),
    ]
