# Generated by Django 3.2 on 2021-04-18 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transferences', '0004_alter_transfer_origin_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='origin_account',
            field=models.CharField(max_length=200, verbose_name='Cuenta de origen'),
        ),
    ]
