# Generated by Django 3.2 on 2021-04-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Moneda')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Logo')),
                ('amount', models.FloatField(verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
        ),
    ]
