# Generated by Django 3.2 on 2021-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='price',
            field=models.FloatField(default=True, verbose_name='Cotizacion'),
        ),
    ]
