# Generated by Django 3.2 on 2021-04-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Currencies', '0002_currency_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
