# Generated by Django 3.2 on 2021-04-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Currencies', '0003_currency_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.FloatField(verbose_name='Cotizacion'),
        ),
    ]
