# Generated by Django 3.2 on 2021-04-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Currencies', '0004_alter_currency_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
