# Generated by Django 3.2 on 2021-04-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paypal', '0003_alter_product_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
