# Generated by Django 3.2 on 2021-04-19 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Currencies', '0003_currency_update_date'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('account_number', 'type_currency')},
        ),
    ]
