# Generated by Django 3.2 on 2021-04-20 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Currencies', '0004_alter_currency_price'),
        ('Accounts', '0004_alter_account_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('account_number', 'type_currency')},
        ),
    ]
